Create entrypoint
ozoncp/ocp-quiz-api pull request #1
Opened 2021-07-14 08:38 UTC by kireevys

2021-07-18 14:27 UTC, rusdevops approved these changes

2021-07-18 14:28 UTC, rusdevops reviewed
пакет нужно назвать cmd/ocp-quiz-api
попрошу добавить go.mod файл

2021-07-19 15:17 UTC, LiFeAiR requested changes
поддержу предидущего ревьюэра
ocp-quiz-ap -> ocp-quiz-api
+ добавь файл go.sum

2021-07-19 15:30 UTC, kireevys commented
Вроде готово. У меня еще нет зависимостей, я полагаю, go.sum и должен быть пустым?

2021-07-21 08:18 UTC, LiFeAiR approved these changes

2021-07-21 09:01 UTC, merged