Задание III
ozoncp/ocp-quiz-api pull request #3
Opened 2021-07-23 18:24 UTC by kireevys

Используя defer и функтор реализовать открытие и закрытие файла в цикле (конфигурационного файла на пример)
Для своей предметной области описать структуры и
реализовать методы работы с ними к примеру String()
type Entity struct {
 UserId uint64
 // ...
}
3. Реализовать в пакете internal/utils для своей структуры функции:
Батчевого разделения слайса на слайс слайсов, на пример:
func SplitToBulks(entities []Entity, butchSize uint)[][]Entity {
}
Конвертации слайса от структуры в отображение,
       где ключ идентификатор структуры, а значение сама структура, на пример:
func ...(entities []Entity) (map[uint64]Entity, error) {
}

2021-07-23 18:45 UTC, LiFeAiR requested changes

2021-07-23 18:45 UTC, LiFeAiR commented on internal/utils/sliceToMap_test.go
> +	"github.com/ozoncp/ocp-quiz-api/internal/models"
придерживайся пожалуйста такого принципа сортировки пакетов
```
//гошное
"context"
"os"
"time"

//внутреннее сервиса
"gitlab.ozon.ru/shock/gateway/internal/pkg/acl"
"gitlab.ozon.ru/shock/gateway/internal/pkg/t"

//3rd-party
"github.com/opentracing/opentracing-go"
"gitlab.ozon.ru/platform/errors"
```
комментарии можешь не писать)

2021-07-23 18:45 UTC, LiFeAiR commented on internal/utils/splitToBulks_test.go
> +	"github.com/ozoncp/ocp-quiz-api/internal/models"
сортировка

2021-07-25 23:18 UTC, kireevys commented on internal/utils/splitToBulks_test.go
> +	"github.com/ozoncp/ocp-quiz-api/internal/models"
Поправил, настроил форматировщик

2021-07-26 14:06 UTC, LiFeAiR approved these changes

2021-07-26 14:08 UTC, merged