Task 6
ozoncp/ocp-quiz-api pull request #6
Opened 2021-08-19 16:51 UTC by kireevys

Нужно реализовать CRUD сервис, для хранения информации для Вашей главной сущности
ручки будут CreateEntity , DescribeEntity, ListEntities, RemoveEntity - для синхронного общения (gRPC). Entity - для примера
Нужно описать proto файлы и сгенерировать код в pkg директорию
Makefile можно посмотреть в ocp-task-api
Имплементация ручек - просто логгирование с помощью zerolog
Добавить в cmd/ocp-entity-api/main.go код по поднятию gRPC сервиса
Пока деплой локальный

2021-08-20 09:11 UTC, LiFeAiR requested changes

2021-08-20 09:11 UTC, LiFeAiR commented on Makefile
> +		go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
тут все теки лучше фиксировать версии зависимостей, иначе в конце концов можно получить несовместимую версию и все сломается

2021-08-20 09:11 UTC, LiFeAiR commented on api/ocp-quiz-api/ocp_quiz_api.proto
> +  uint64 ClassroomId = 2;
у нас в протобафе для имен полей принято придерживаться _snake_case_ нотации

2021-08-20 09:11 UTC, LiFeAiR commented on api/ocp-quiz-api/ocp_quiz_api.proto
> +  uint64  UserId = 2 [(validate.rules).uint64.gt = 0];
тут что то с кодинг стайном

2021-08-22 13:28 UTC, kireevys commented on Makefile
> +		go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
Поправил

2021-08-23 08:12 UTC, LiFeAiR approved these changes

2021-08-24 12:33 UTC, merged